"use client";

import React from "react";
import Link from "next/link";
import { HiArrowUpRight } from "react-icons/hi2";

export function ActiveRolesSidebar({ roles, hiringTeam = [] }) {
  const activeRoles = Array.isArray(roles) ? roles : [];
  const team = Array.isArray(hiringTeam) ? hiringTeam : [];

  return <div className="space-y-6"><div className="rounded-2xl border border-white/10 bg-[#0b0b0f]/80 p-6 backdrop-blur-xl"><div className="mb-5 flex items-center justify-between"><h3 className="text-sm font-bold text-white">Active Roles</h3><span className="rounded-full bg-white/10 px-2 py-0.5 text-[10px] font-bold text-gray-300">{activeRoles.length}</span></div>{activeRoles.length ? <div className="space-y-3">{activeRoles.map((role) => <Link href={role._id ? `/jobs/${role._id}` : "/dashboard/recruiter/jobs"} key={role._id || role.title} className="block space-y-3 rounded-xl border border-white/5 bg-white/[.02] p-4 transition hover:bg-white/5"><div className="flex items-start justify-between gap-2"><h4 className="text-xs font-semibold leading-snug text-white">{role.title}</h4><HiArrowUpRight className="shrink-0 text-sm text-gray-500" /></div><div className="flex flex-wrap items-center gap-2 text-[10px] font-medium text-gray-400"><span className="rounded border border-white/10 bg-white/5 px-2 py-0.5">{role.location || "Location not listed"}</span><span className="rounded border border-white/10 bg-white/5 px-2 py-0.5">{role.salaryRange || role.salary || "Salary not listed"}</span></div></Link>)}</div> : <p className="rounded-xl border border-dashed border-white/10 p-5 text-center text-xs text-gray-500">No active roles available from the API.</p>}<Link href="/dashboard/recruiter/jobs" className="mt-4 block w-full rounded-xl border border-white/10 bg-white/5 py-2.5 text-center text-xs font-medium text-gray-300 transition hover:bg-white/10">See all {activeRoles.length} openings</Link></div><div className="space-y-4 rounded-2xl border border-white/10 bg-[#0b0b0f]/80 p-6 backdrop-blur-xl"><h3 className="text-xs font-bold uppercase tracking-wider text-gray-400">Hiring Team</h3>{team.length ? team.map((member) => <div key={member._id || member.email} className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center overflow-hidden rounded-full border border-white/10 bg-white/5 text-xs font-bold text-gray-400">{member.image ? <img src={member.image} alt="" className="h-full w-full object-cover" /> : member.name?.[0]?.toUpperCase() || "?"}</div><div><p className="text-xs font-bold text-white">{member.name || "Team member"}</p><p className="text-[10px] text-gray-500">{member.title || member.role || "Hiring team"}</p></div></div>) : <p className="text-xs text-gray-500">No hiring team data available.</p>}</div></div>;
}
