"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import Link from "next/link";
import { authClient } from "@/lib/auth-client";
import { HiBriefcase, HiChartBar, HiClock, HiDocumentText } from "react-icons/hi2";
import toast from "react-hot-toast";

const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:5050/api";
const getToken = async () => (await authClient.getSession()).data?.session?.token;

export default function AdminJobsPage() {
  const searchParams = useSearchParams();
  const query = searchParams.get("q") || "";
  const [jobs, setJobs] = useState([]); const [status, setStatus] = useState("all"); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { try { setLoading(true); const res = await fetch(`${API}/admin/jobs`, { headers: { Authorization: `Bearer ${await getToken()}` }, credentials: "include" }); const json = await res.json(); if (!res.ok) throw new Error(json.message); setJobs(json.data || []); } catch (e) { toast.error(e.message || "Failed to load jobs"); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const filtered = useMemo(() => jobs.filter((j) => (!query || `${j.title} ${j.companyName}`.toLowerCase().includes(query.toLowerCase())) && (status === "all" || j.status === status)), [jobs, query, status]);
  const moderate = async (id, action) => { try { const endpoint = action === "delete" ? `${API}/admin/jobs/${id}` : `${API}/admin/jobs/${id}/${action}`; const res = await fetch(endpoint, { method: action === "delete" ? "DELETE" : "PATCH", headers: { Authorization: `Bearer ${await getToken()}` }, credentials: "include" }); const json = await res.json(); if (!res.ok) throw new Error(json.message); toast.success(json.message || "Updated"); load(); } catch (e) { toast.error(e.message || "Action failed"); } };
  const cards = [["Active Jobs", jobs.filter((j) => j.status === "active").length, HiBriefcase], ["Closed Jobs", jobs.filter((j) => j.status === "closed").length, HiClock], ["Total Applications", jobs.reduce((n, j) => n + Number(j.applicantsCount || 0), 0), HiDocumentText], ["Visible Results", filtered.length, HiChartBar]];
  return <main className="space-y-7 text-white"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[.22em] text-indigo-400">Admin Console</p><h1 className="mt-2 text-3xl font-bold">Manage Jobs</h1><p className="mt-1 text-sm text-gray-400">Oversee all active listings and historical job posts.</p></div><div className="flex shrink-0 flex-nowrap items-center gap-2"><select aria-label="Filter jobs by status" value={status} onChange={(e) => setStatus(e.target.value)} className="rounded-xl border border-white/10 bg-[#111118] px-4 py-2.5 text-xs text-white"><option value="all">All Statuses</option><option value="active">Active</option><option value="closed">Closed</option><option value="draft">Draft</option></select><Link href="/dashboard/recruiter/jobs/new" className="shrink-0 rounded-xl bg-white px-4 py-2.5 text-xs font-semibold text-black">+ Create Job</Link></div></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, Icon]) => <div key={label} className="rounded-2xl border border-white/10 bg-[#151519] p-5"><div className="flex justify-between text-gray-400"><span className="text-[11px]">{label}</span><Icon className="text-lg text-indigo-400" /></div><p className="mt-3 text-2xl font-bold">{value}</p></div>)}</div><div className="overflow-x-auto rounded-2xl border border-white/10 bg-[#151519]"><table className="w-full min-w-[1000px] text-left text-xs"><thead className="border-b border-white/10 text-[10px] uppercase text-gray-500"><tr><th className="p-4">Title</th><th className="p-4">Company</th><th className="p-4">Category</th><th className="p-4">Type</th><th className="p-4">Date Posted</th><th className="p-4">Status</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{loading ? <tr><td className="p-8 text-center" colSpan="7">Loading…</td></tr> : filtered.map((job) => <tr key={job._id} className="border-b border-white/5"><td className="p-4 font-medium"><Link href={`/jobs/${job._id}`} className="hover:text-cyan-300">{job.title || "Untitled"}</Link><div className="text-[10px] text-gray-500">Ref: {String(job._id).slice(-8)}</div></td><td className="p-4 text-gray-300">{job.companyName || "—"}</td><td className="p-4 text-gray-400">{job.category || "Other"}</td><td className="p-4 text-gray-400">{job.jobType || "—"}</td><td className="p-4 text-gray-400">{job.createdAt ? new Date(job.createdAt).toLocaleDateString() : "—"}</td><td className="p-4"><span className={`rounded-full px-2 py-1 text-[10px] ${job.status === "active" ? "bg-emerald-400/10 text-emerald-300" : "bg-white/10 text-gray-300"}`}>{job.status}</span></td><td className="p-4 text-right"><Link href={`/jobs/${job._id}`} className="mr-3 text-[10px] text-cyan-300">View</Link><button onClick={() => moderate(job._id, job.status === "active" ? "close" : "delete")} className="text-[10px] text-red-300">{job.status === "active" ? "Close" : "Remove"}</button></td></tr>)}</tbody></table></div></main>;
}
